### ISSUE TITLE
An error occurs when running on a Windows 7 32-bit system

### ISSUE THREAD

**Issue by haohetao** [FlaUI/FlaUInspect#18]
![error](https://user-images.githubusercontent.com/4592571/133200711-c395c9bf-a9e6-402d-a83d-67e796a82b4e.png)

**Comment by siggipop** [comment]
What does error message say in your local language?

**Comment by haohetao** [comment]
@siggipop 
values are not in the expected range.

**Comment by luoyulong-CQMU** [comment]
i also see the same error when run the app on windows7；

**Comment by a9038889** [comment]
I also see the same error when run the app on windows7；And if you use version 1.2.0, there is no problem~

**Comment by Anton-V-K** [comment]
Any chances this issue can be fixed somehow?
Same issue happens both in 32-bit, and 64-bit Windows 7.
Maybe some component or update is missing in the system?

For references - text representation of the exception:
```
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Value does not fall within the expected range.
   at Interop.UIAutomationClient.IUIAutomationElement.GetCurrentPropertyValueEx(Int32 propertyId, Int32 ignoreDefaultValue)
   at FlaUI.UIA3.UIA3FrameworkAutomationElement.InternalGetPropertyValue(Int32 propertyId, Boolean cached, Boolean useDefaultIfNotSupported)
   at FlaUI.Core.FrameworkAutomationElementBase.TryGetPropertyValue[T](PropertyId property, T& value)
   at FlaUI.Core.AutomationElements.AutomationElement.IsPatternSupported(PatternId pattern)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FlaUI.Core.AutomationElements.AutomationElement.GetSupportedPatterns()
   at FlaUInspect.ViewModels.ElementViewModel.LoadDetails()
   at FlaUInspect.ViewModels.ElementViewModel.<set_IsSelected>b__9_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: Value does not fall within the expected range.
   at Interop.UIAutomationClient.IUIAutomationElement.GetCurrentPropertyValueEx(Int32 propertyId, Int32 ignoreDefaultValue)
   at FlaUI.UIA3.UIA3FrameworkAutomationElement.InternalGetPropertyValue(Int32 propertyId, Boolean cached, Boolean useDefaultIfNotSupported)
   at FlaUI.Core.FrameworkAutomationElementBase.TryGetPropertyValue[T](PropertyId property, T& value)
   at FlaUI.Core.AutomationElements.AutomationElement.IsPatternSupported(PatternId pattern)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FlaUI.Core.AutomationElements.AutomationElement.GetSupportedPatterns()
   at FlaUInspect.ViewModels.ElementViewModel.LoadDetails()
   at FlaUInspect.ViewModels.ElementViewModel.<set_IsSelected>b__9_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```
